Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Style/PreferredHashMethods:
  EnforcedStyle: verbose

Style/RedundantReturn:
  Enabled: false

Style/TrivialAccessors:
  IgnoreClassMethods: true

Style/Documentation:
  Enabled: false
