Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Metrics/ModuleLength:
  Enabled: false

Style/PredicateName:
  Enabled: false

Style/PreferredHashMethods:
  EnforcedStyle: verbose

Style/RedundantReturn:
  Enabled: false

Style/TrivialAccessors:
  IgnoreClassMethods: true

Style/Documentation:
  Enabled: false

Style/IndentHeredoc:
  Enabled: false

Style/EmptyElse:
  EnforcedStyle: empty

Style/SymbolArray:
  Enabled: false

Style/RaiseArgs:
  Enabled: false
